before_script:
    - 'apt-get update'
    - 'apt-get -y install nuget mono-devel mono-xbuild'
    - 'nuget update -self'
    - 'nuget restore test.sln'

build_job:
  stage: build
  
  script:
    - 'xbuild test.sln'
    - 'ls'
