before_script:
    - 'apt-get update'
    - 'apt-get -y install nuget msbuild'
    - 'nuget restore test.sln'

build_job:
  stage: build
  
  script:
    - 'msbuild test.sln /t:Clean,ReBuild /p:Configuration=Debug;Platform="Any CPU"'
