image: mcr.microsoft.com/dotnet/core/samples

before_script:
    - 'apt-get update'
    - 'apt-get -y install nuget msbuild'
    - 'nuget update -self'
    - 'nuget restore test.sln'

build_job:
  stage: build
  
  script:
    - 'msbuild test.sln'
    - 'ls'
