image: docker pull mcr.microsoft.com/dotnet/sdk:5.0

before_script:
    - 'apt-get update'
    #- 'apt-get -y install nuget msbuild'
    #- 'nuget update -self'
    #- 'nuget restore test.sln'

build_job:
  stage: build
  
  script:
    #- 'msbuild test.sln'
    - 'dotnet build test.sln'
    - 'ls'
