image: mcr.microsoft.com/dotnet/framework/sdk:4.8

before_script:
    - 'apt-get update'
    #- 'apt-get -y install nuget msbuild'
    #- 'nuget update -self'
    #- 'nuget restore test.sln'
    - 'dotnet --info'

build_job:
  stage: build
  
  script:
    #- 'msbuild test.sln'
    - 'dotnet build test.sln'
    - 'ls'
